USE MASTER
GO
DROP DATABASE IF EXISTS QuanLyCuaHangMayTinh
GO
CREATE DATABASE QuanLyCuaHangMayTinh
GO
USE QuanLyCuaHangMayTinh
--TAO BANG
GO
CREATE  TABLE KHACHHANG(
    MAKH CHAR(10) PRIMARY KEY, --MAKH SINH TU DONG
    TENKH NVARCHAR(50) NOT NULL,
    SDT CHAR(10),
)
GO
CREATE TABLE NHANVIEN(
    MANV CHAR(10) PRIMARY KEY,
    MATKHAU CHAR(10) NOT NULL,
    TENNV NVARCHAR(50) NOT NULL,
    NGAYSINH DATETIME,
    QUEQUAN NVARCHAR(100)
)
GO
CREATE TABLE SANPHAM(
    MASP CHAR(10) PRIMARY KEY,
    TENSP NVARCHAR(50),
    MAU NVARCHAR(50) NOT NULL,
    CAUHINH NVARCHAR(30) NOT NULL,
    GIABAN FLOAT NOT NULL
)
GO
CREATE TABLE HOADONBAN(
    MAHDB CHAR(10) PRIMARY KEY,
    NGAYBAN DATETIME,
    MANV CHAR(10) NOT NULL,
    MAKH CHAR(10) NOT NULL
)
GO
CREATE TABLE CHITIETHDB(
    MAHDB CHAR(10) NOT NULL,
    MASP CHAR(10) NOT NULL,
    SOLUONG INT
)
GO
--INSERT DU LIEU
--KHACH HANG
INSERT INTO KHACHHANG VALUES('KH1','TRAN VAN A','013541251')
INSERT INTO KHACHHANG VALUES('KH2','TRAN VAN B','013541252')
INSERT INTO KHACHHANG VALUES('KH3','TRAN VAN C','013541254')
INSERT INTO KHACHHANG VALUES('KH4','TRAN VAN D','013544251')
INSERT INTO KHACHHANG VALUES('KH5','TRAN VAN E','013541251')
INSERT INTO KHACHHANG VALUES('KH6','TRAN VAN G','013001251')
INSERT INTO KHACHHANG VALUES('KH7','TRAN VAN H','013541111')
INSERT INTO KHACHHANG VALUES('KH8','TRAN VAN I','013541251')
INSERT INTO KHACHHANG VALUES('KH9','TRAN VAN K','013441251')
INSERT INTO KHACHHANG VALUES('KH10','TRAN VAN M','013441231')

--NHANVIEN
GO
INSERT INTO NHANVIEN VALUES('NV1','123','NGUYEN THANH A','2001/03/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV2','123','NGUYEN THANH B','2000/03/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV3','123','NGUYEN THANH C','2002/03/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV4','123','NGUYEN THANH D','2003/03/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV5','123','NGUYEN THANH E','2001/04/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV6','123','NGUYEN THANH G','2001/09/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV7','123','NGUYEN THANH H','2001/04/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV8','123','NGUYEN THANH I','2001/01/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV9','123','NGUYEN THANH K','2001/09/15','HUNG YEN');
INSERT INTO NHANVIEN VALUES('NV10','123','NGUYEN THANH L','2001/12/15','HUNG YEN');
GO
--Các thủ tục
----------------------------------------------------------------
--XEM KHÁCH HÀNG
GO

--THÊM KHÁCH HÀNG
CREATE PROCEDURE USP_THEMKHACHHANG
                @MAKH CHAR(10),@TENKH NVARCHAR(50),@SDT CHAR(10)
AS
BEGIN
    INSERT INTO KHACHHANG
    VALUES(@MAKH,@TENKH,@SDT)
END
GO
--SỬA KHÁCH HÀNG
CREATE PROCEDURE USP_SUAKHACHHANG
                @MAKH CHAR(10),@TENKH NVARCHAR(50),@SDT CHAR(10)
AS
BEGIN
    UPDATE KHACHHANG SET TENKH =@TENKH,SDT =@SDT
    WHERE MAKH =@MAKH
END
GO
-- XÓA KHÁCH HÀNG
CREATE PROCEDURE USP_XOAKHACHHANG
                    @MAKH CHAR(10)
AS
BEGIN
    DELETE FROM KHACHHANG WHERE MAKH =@MAKH
END
GO
--TÌM KIẾM KHÁCH HÀNG
CREATE PROCEDURE USP_TIMKIEMKHACHHANG
                    @TUKHOA NVARCHAR(50)
AS
BEGIN
    SELECT * FROM KHACHHANG WHERE Khachhang.TENKH = @TUKHOA OR TENKH LIKE @TUKHOA OR SDT LIKE @TUKHOA OR TENKH LIKE '%'+@TUKHOA+'%'
END

GO
--THÊM NHÂN VIÊN
CREATE PROCEDURE USP_THEMNHANVIEN
                    @MANV CHAR(10),@MATKHAU CHAR(10),@TENNV NVARCHAR(50),@NGAYSINH DATETIME,@QUEQUAN VARCHAR(100)
AS
BEGIN
    INSERT INTO NHANVIEN VALUES (@MANV,@MATKHAU,@TENNV,@NGAYSINH+'',@QUEQUAN)
END
GO

GO
--SỬA NHÂN VIÊN
CREATE PROCEDURE USP_SUANHANVIEN
                    @MANV CHAR(10),@MATKHAU CHAR(10),@TENNV NVARCHAR(50),@NGAYSINH DATETIME,@QUEQUAN VARCHAR(100)
AS
BEGIN
    UPDATE NHANVIEN SET MATKHAU = @MATKHAU,TENNV= @TENNV,NGAYSINH= @NGAYSINH+'',QUEQUAN =@QUEQUAN
    WHERE MANV = @MANV
END
GO
--XOA NHAN VIEN
CREATE PROCEDURE USP_XOANHANVIEN
                    @MANV CHAR(10)
AS
BEGIN
    DELETE FROM NHANVIEN WHERE MANV = @MANV
END
GO
--TIM KIEM NHAN VIEN
CREATE PROCEDURE USP_TIMKIEMNHANVIEN @TUKHOA NVARCHAR(30)
AS
BEGIN
    SELECT * FROM NHANVIEN WHERE MANV LIKE @TUKHOA OR TENNV LIKE '%'+@TUKHOA+'%'
END
GO


--HÀM
----------------------------------------------------------------

GO
-- THEM SAN PHAM
CREATE PROCEDURE USP_THEMSP @MASP CHAR(10),@TENSP NVARCHAR(50),@MAU NVARCHAR(50),@CAUHINH NVARCHAR(30),@GIABAN FLOAT
AS
BEGIN
    INSERT INTO SANPHAM VALUES(@MASP,@TENSP,@MAU,@CAUHINH,@GIABAN)
END
GO
-- SUA SAN PHAM
CREATE PROCEDURE USP_SUASP  @MASP CHAR(10),@TENSP NVARCHAR(50),@MAU NVARCHAR(50),@CAUHINH NVARCHAR(30),@GIABAN FLOAT
AS
BEGIN
    UPDATE SANPHAM SET TENSP = @TENSP,MAU = @MAU,CAUHINH = @CAUHINH,GIABAN = @GIABAN WHERE MASP = @MASP
END
GO
--XOA SAN PHAM
CREATE PROCEDURE USP_XOASP @MASP CHAR(10)
AS
BEGIN
    DELETE FROM SANPHAM WHERE MASP = @MASP
END
GO
--TIM KIEM SAN PHAM
CREATE PROCEDURE USP_TIMKIEMSP @TUKHOA NVARCHAR(30)
AS
BEGIN
    SELECT * FROM SANPHAM WHERE MASP = @TUKHOA OR TENSP = @TUKHOA
END

-- XEM DANH SACH SAN PHAM
GO
CREATE VIEW VIEW_DSSANPHAM AS
SELECT * FROM SANPHAM
GO
--THEM HOA DON BAN
CREATE PROCEDURE USP_THEMHOADONBAN @MAHDB CHAR(10) ,@NGAYBAN DATETIME,@MANV CHAR(10),@MAKH CHAR(10)
AS
BEGIN
    INSERT INTO HOADONBAN
    VALUES(@MAHDB,@NGAYBAN+'',@MANV,@MAKH)
END
GO
--THEM CHI TIET HOA DON BAN
CREATE PROCEDURE USP_THEMCHITIETHDB @MAHDB CHAR(10),@MASP CHAR(10),@SOLUONG INT
AS
BEGIN
    INSERT INTO CHITIETHDB VALUES (@MAHDB,@MASP,@SOLUONG)
END
GO
--XEM THONGTINHOADON
CREATE VIEW VIEW_THONGTINHOADON AS
SELECT HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,CHITIETHDB.MASP,CHITIETHDB.SOLUONG FROM HOADONBAN,CHITIETHDB WHERE HOADONBAN.MAHDB = CHITIETHDB.MAHDB
GO
--XEM THONG TIN HOA DON BAN
CREATE VIEW VIEW_HOADONBAN AS
SELECT HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,SANPHAM.TENSP,CHITIETHDB.SOLUONG,SANPHAM.GIABAN FROM HOADONBAN,CHITIETHDB,SANPHAM WHERE HOADONBAN.MAHDB = CHITIETHDB.MAHDB AND CHITIETHDB.MASP = SANPHAM.MASP
GO
--XEM HOA DON THANH TOAN
GO
CREATE VIEW VIEW_HOADONTHANHTOAN AS
SELECT HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,KHACHHANG.TENKH,SUM(CHITIETHDB.SOLUONG) [SO LUONG MUA],SUM(CHITIETHDB.SOLUONG*SANPHAM.GIABAN) [TONG THANH TOAN] FROM HOADONBAN,CHITIETHDB,SANPHAM,KHACHHANG,NHANVIEN WHERE HOADONBAN.MAHDB = CHITIETHDB.MAHDB AND HOADONBAN.MAKH = KHACHHANG.MAKH AND HOADONBAN.MANV = NHANVIEN.MANV AND CHITIETHDB.MASP = SANPHAM.MASP
GROUP BY HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,KHACHHANG.TENKH
GO
--XEM CHITIETHDB THEO MAHDB
CREATE PROCEDURE USP_CHITIETHDB @MAHDB CHAR(10)
AS
BEGIN
SELECT HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,CHITIETHDB.MASP,CHITIETHDB.SOLUONG FROM HOADONBAN,CHITIETHDB WHERE HOADONBAN.MAHDB = @MAHDB AND HOADONBAN.MAHDB = CHITIETHDB.MAHDB
END
go
select * from hoadonban
select * from CHITIETHDB

-- XEM HOA DON THANH TOAN THEO MAHDB
GO
CREATE PROCEDURE USP_HOADONTHANHTOAN @MAHDB CHAR(10)
AS
BEGIN
    SELECT HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,KHACHHANG.TENKH,SUM(CHITIETHDB.SOLUONG) [SO LUONG MUA],SUM(CHITIETHDB.SOLUONG*SANPHAM.GIABAN) [TONG THANH TOAN] FROM HOADONBAN,CHITIETHDB,SANPHAM,KHACHHANG,NHANVIEN WHERE HOADONBAN.MAHDB = CHITIETHDB.MAHDB AND HOADONBAN.MAKH = KHACHHANG.MAKH AND HOADONBAN.MANV = NHANVIEN.MANV AND CHITIETHDB.MASP = SANPHAM.MASP AND HOADONBAN.MAHDB = @MAHDB
GROUP BY HOADONBAN.MAHDB,HOADONBAN.NGAYBAN,KHACHHANG.TENKH
END
--------------------------------------------------------------------------------------
--HAM
--------------------------------------------------------------------------------------
GO

create proc ThongKe
as
begin
    select HOADONBAN.NGAYBAN,SUM(CHITIETHDB.SOLUONG*SANPHAM.GIABAN) [TongTien] 
    from HOADONBAN,CHITIETHDB,SANPHAM 
    where HOADONBAN.MAHDB = CHITIETHDB.MAHDB and SANPHAM.MASP = CHITIETHDB.MASP
    group by HOADONBAN.NGAYBAN
end
go
create proc ThongKeBanChay
as
begin
    select TOP 5 SANPHAM.TENSP,SANPHAM.GIABAN, COUNT(CHITIETHDB.SOLUONG)[SO LUONG BAN] from SANPHAM,CHITIETHDB WHERE SANPHAM.MASP = CHITIETHDB.MASP
    GROUP BY SANPHAM.TENSP,SANPHAM.GIABAN
    ORDER BY  COUNT(CHITIETHDB.SOLUONG) DESC
end
go
CREATE VIEW VIEW_DSKHACHHANG
AS
    SELECT * FROM KHACHHANG
GO